inputs:
  AWS:
    awsAccounts:
      - accountID: "296712556520"
        accessKey: "AKIAUKFLSJ7UBYOJXFQ4"
        secretAccessKey: "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"
        scanAllBuckets: true
        buckets: []
  Microsoft:
    onedriveAccounts:
      - tenant_id: "dc843d33-976c-43d8-9e0b-6fa802986077"
        client_id: "8593b514-f63c-43dd-86eb-f035f506ebeb"
        client_secret: "6oj8Q~fwPZ7OoG-kTbcVJe5ZVSCCZ5Iq3OV_IcL3"
        scanAllUsers: true
        scanUsers: 
          - "admin@skyhighlabs.onmicrosoft.com"


storage:
  AWS:
    accountID: "296712556520"
    accessKey: "AKIAUKFLSJ7UBYOJXFQ4"
    secretAccessKey: "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"
    bucketName: "skyhigh-ndexer-output-fs1dfwe4"
    awsHashIndexFile: "s3-fileindex.csv"
    onedriveIndexFile: "onedrive-fileindex.csv"
    microsoftMetadataDB: "hashes.db"
    retainFiles: true


